version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    volumes: 
      - ./flask:/src
    expose: 
      - "5000"
    links:
      - redis
    tty: true
    restart: always
  
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    volumes: 
      - ./data/redis:/data
    command: >
      sh -c "redis-server --appendonly yes"
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "5000:80"

    
