version: '3'

services:
  flask:
    build: .
    volumes:
      - ./src:/usr/src
    ports:
      - "5000:5000"
    links:
      - redis
    tty: true
  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: >
      sh -c "redis-server --appendonly yes"
    
