version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    volumes: 
      - ./flask:/src
    expose: 
      - "5000"
    links:
      - redis
      - postgreSQL
    tty: true
    restart: always
  
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    volumes: 
      - ./data/redis:/data
    command: >
      sh -c "redis-server --appendonly yes"
    restart: always
  
  postgreSQL:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/PostgreSQL:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - flask
    ports: 
      - "5000:80"

    
